media:
  input: img
  output: img
content:
  - name: global
    label: Global Settings (Menu/Titles)
    type: file
    path: content/global.json
    format: json
    fields:
      - name: logo_alt
        label: Logo Alt Text
        type: string
      - name: titles
        label: Page Titles
        type: object
        fields:
          - name: articles
            label: Articles Page Title
            type: string
          - name: awards
            label: Awards Page Title
            type: string
      - name: nav
        label: Navigation Menu
        type: list
        item_label: label
        fields:
          - name: label
            label: Menu Label
            type: string
          - name: url
            label: Page URL
            type: string
      - name: footer_rights
        label: Footer Text
        type: string

  - name: home
    label: Home Page
    type: file
    path: content/home.json
    format: json
    fields:
      - name: hero_title
        label: Main Headline
        type: string
      - name: hero_subtitle
        label: Subtitle Description
        type: string
      - name: cta_button
        label: Button Text
        type: string

  - name: about
    label: About Page
    type: file
    path: content/about.json
    format: json
    fields:
      - name: title
        label: Page Title
        type: string
      - name: content_paragraphs
        label: Content
        type: list
        fields:
          - name: paragraph
            label: Text Block
            type: text

  - name: articles
    label: Articles List
    type: file
    path: content/articles.json
    format: json
    list: true
    item_label: title
    fields:
      - name: id
        label: URL Slug (ID)
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: authors
        label: Authors
        type: string
      - name: date
        label: Date
        type: date
      - name: abstract
        label: Abstract
        type: text
      - name: introduction
        label: Introduction
        type: rich-text
      - name: methods
        label: Methods
        type: rich-text
      - name: results
        label: Results
        type: rich-text
      - name: discussion
        label: Discussion
        type: rich-text
      - name: conclusion
        label: Conclusion
        type: rich-text
      - name: references
        label: References
        type: list
        fields:
          - name: citation
            type: string

  - name: awards
    label: Awards List
    type: file
    path: content/awards.json
    format: json
    list: true
    item_label: title
    fields:
      - name: title
        label: Award Title
        type: string
      - name: description
        label: Description
        type: string

  - name: contact
    label: Contact Page
    type: file
    path: content/contact.json
    format: json
    fields:
      - name: title
        label: Page Title
        type: string
      - name: form
        label: For Labels
        type: object
        fields:
          - name: name_label
            type: string
          - name: email_label
            type: string
          - name: message_label
            type: string
          - name: submit_btn
            type: string
