
{
    "common": {
        "logo_alt": "Personal Logo",
        "nav": {
            "home": "Home",
            "about": "About",
            "articles": "Articles",
            "awards": "Awards",
            "contact": "Contact"
        },
        "footer_rights": "GY LIM. All Rights Reserved."
    },
    "home": {
        "hero_title": "Professional Solutions.<br>Medical Precision.",
        "hero_subtitle": "I blend professional expertise with clinical precision to deliver outstanding results. Welcome to my portfolio.",
        "cta_button": "Get in Touch"
    },
    "about": {
        "title": "About Me",
        "content_paragraphs": [
            "With a dedication to excellence and a keen eye for detail, I strive to bridge the gap between complex problems and elegant solutions. My background allows me to approach challenges with a unique perspective, ensuring thoroughness and quality in every project.",
            "I specialize in delivering high-quality work that meets the rigorous standards of today's professional landscape."
        ]
    },
    "awards": {
        "title": "Honors & Awards",
        "awards_list": [
            {
                "title": "Project Alpha",
                "description": "A comprehensive study on clinical data efficiency."
            },
            {
                "title": "Project Beta",
                "description": "Strategic medical device implementation plan."
            },
            {
                "title": "Project Gamma",
                "description": "Professional consultation framework development."
            }
        ]
    },
    "contact": {
        "title": "Contact Me",
        "form": {
            "name_label": "Name",
            "email_label": "Email",
            "message_label": "Message",
            "submit_btn": "Send Message"
        }
    },
    "articles": [
        {
            "id": "sample-article-1",
            "title": "Sample Medical Article: The Impact of Modern Tech",
            "authors": "G.Y. Lim",
            "date": "2026-03-15",
            "abstract": "This is a sample abstract summary of the article. It provides an overview of the research and findings...",
            "introduction": "Here is the introduction section text. It fills out the necessary background info...",
            "methods": "Detailed methods used in this study go here...",
            "results": "These are the findings of the study...",
            "discussion": "Interpreting the results...",
            "conclusion": "Final thoughts and summary...",
            "references": [
                "Smith J, et al. Journal of Medical Things. 2025;12(3):45-50.",
                "Doe A. Future Medicine. 2024;8(1):112-118."
            ]
        },
        {
            "id": "sample-article-2",
            "title": "Incomplete Section Example",
            "authors": "G.Y. Lim",
            "date": "2026-04-01",
            "abstract": "This article demonstrates how empty sections are hidden. Only Introduction and Conclusion are provided.",
            "introduction": "This is the only main content section provided aside from abstract and conclusion.",
            "methods": "",
            "results": "",
            "discussion": "",
            "conclusion": "As you can see, methods, results, and discussion sections are hidden.",
            "references": []
        }
    ]
}